<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-35602c
Date:    2018-02-14 17:12:08
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-35602c",
    "email": {
        "to": "aram@hoopscollege.com",
        "cc": "",
        "bcc": "",
        "subject": "Coach's Consultation Online",
        "template": ""
    },
    "admin": {
        "users": "admin:8ec1b, aram:D1ck0987!",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "ccffthankyou.html",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": false,
        "subject": "Coach's Consultation ",
        "template": "Thank you for filling out the questionnaire.",
        "replyTo": "aram@hoopscollege.com",
        "replyToName": "Aram Parunak"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "hidden": false
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Number",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "id": "f4",
            "cid": "c27"
        },
        {
            "label": "Number Copy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "cid": "c32",
            "id": "f5"
        },
        {
            "label": "Number Copy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "cid": "c38",
            "id": "f6"
        },
        {
            "label": "Number Copy Copy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "cid": "c50",
            "id": "f8"
        },
        {
            "label": "Number Copy Copy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "cid": "c56",
            "id": "f9"
        },
        {
            "label": "Number Copy Copy Copy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "10",
                    "initval": "0",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "cid": "c63",
            "id": "f10"
        },
        {
            "label": "Multiple Choice",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Corrosive",
                        "checked": false,
                        "value": "Corrosive"
                    },
                    {
                        "label": "Country Club",
                        "checked": false,
                        "value": "Country_Club"
                    },
                    {
                        "label": "Congenial",
                        "checked": false,
                        "value": "Congenial"
                    },
                    {
                        "label": "Comfortable",
                        "checked": null,
                        "value": "Comfortable"
                    },
                    {
                        "label": "Competitive",
                        "checked": null,
                        "value": "Competitive"
                    },
                    {
                        "label": "Cut Throat",
                        "checked": null,
                        "value": "Cut_Throat"
                    },
                    {
                        "label": "Constructive",
                        "checked": null,
                        "value": "Constructuve"
                    },
                    {
                        "label": "Championship",
                        "checked": null,
                        "value": "Championship"
                    }
                ],
                "presetJson": ""
            },
            "id": "f11",
            "cid": "c70"
        },
        {
            "label": "Multiple Choice",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "presetJson": ""
            },
            "id": "f12",
            "cid": "c76"
        },
        {
            "label": "Select",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f13",
            "cid": "c81"
        },
        {
            "label": "Select Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c86",
            "id": "f14"
        },
        {
            "label": "Select Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c92",
            "id": "f15"
        },
        {
            "label": "Select Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c98",
            "id": "f16"
        },
        {
            "label": "Select Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c104",
            "id": "f17"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c110",
            "id": "f18"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c117",
            "id": "f19"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c123",
            "id": "f20"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c129",
            "id": "f21"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c135",
            "id": "f22"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c141",
            "id": "f23"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null,
                        "image": ""
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c147",
            "id": "f24"
        },
        {
            "label": "Select",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f25",
            "cid": "c155"
        },
        {
            "label": "Select Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c160",
            "id": "f26"
        },
        {
            "label": "Select Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c166",
            "id": "f27"
        },
        {
            "label": "Select Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c172",
            "id": "f28"
        },
        {
            "label": "Select Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c178",
            "id": "f29"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c184",
            "id": "f30"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c190",
            "id": "f31"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c196",
            "id": "f32"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c202",
            "id": "f33"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c208",
            "id": "f34"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c214",
            "id": "f35"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c220",
            "id": "f36"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c226",
            "id": "f37"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c232",
            "id": "f38"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c238",
            "id": "f39"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c244",
            "id": "f40"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c250",
            "id": "f41"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c256",
            "id": "f42"
        },
        {
            "label": "Comments",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": "JF-5LF697510M7667901"
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class