<?php

/**
 * This file initializes plugin, once PHP version check passes
 *
 * IMPORTANT, plugins_loaded, priority 1 is the earliest hook you can use.
 */
/**
 * Load the plugin and initialize container
 *
 * @since 2.0.0
 */
add_action('plugins_loaded', 'ninjaFormsHubspotBootstrap', 5);

/**
 * Instantiate NinjaFormsHubspot instance
 */
function ninjaFormsHubspotBootstrap() {


// Include the PSR-4 autoloader
    include_once __DIR__ . '/autoloader.php';

    // Instantiate main instance
    $instance = (new \NFHubspot\NinjaFormsHubspot())
            ->registerServices();

    // Set a NF Bridge package to deliver NF functionality
    $instance->setNfBridge(
            (new NFHubspot\EmailCRM\NfBridge\NfBridge)
                    ->registerServices()
    );

    // Set an API Module to deliver API Module functionality
    $instance->setApiModule(
            (new NFHubspot\EmailCRM\Hubspot\Hubspot())
                    ->registerServices()
    );

    /**
     * Runs directly after creation of main plugin instance
     *
     * @param \NFHubspot\NinjaForms\Hubspot\NinjaFormsHubspot $instance
     * @since 4.0.0
     *
     */
    do_action('nf_hubspot_init', $instance);
}

/**
 * Initiate integrating plugin dependent functionality
 * 
 * @param \NFHubspot\NinjaFormsHubspot  $instance
 */
add_action('nf_hubspot_init', function( $instance) {

    // Register the CreateEntryAction
    $instance->registerCreateEntryAction();

    // Adds modal box to autogenerate form
    add_action('init',function() use ($instance){

        $disableAutogenerateDefault = true;
        
        $disableAutogenerate = apply_filters('nf_hubspot_disable_autogenerator',$disableAutogenerateDefault);
        
        if(!$disableAutogenerate){  
            add_filter('ninja_forms_new_form_templates', [ $instance, 'registerAutogenerateModal' ]);
        }
    },15);
    
    // Initialize WordPress REST API endpoints
    add_action('rest_api_init', [ $instance, 'initRestApi' ]);

    add_action('ninja_forms_loaded', array( $instance, 'setupAdmin' ));
}, 2);

// Register a submission data metabox
add_action('ninja_forms_loaded', function() {
    // Instantiate submission metabox
    new \NFHubspot\EmailCRM\NfBridge\Actions\OutputResponseDataMetabox('add_to_hubspot', 'Hubspot Response');
});


/**
 * Register assets with WordPress
 */
add_action('admin_init', function () {

    //Register asset 
    wp_register_script(
            'nf-hubspot/admin-settings',
            plugins_url('assets/js/admin-settings.js', __FILE__),
            [],
            time()
    );

       $nonce = wp_create_nonce('adminSettings');
       
       wp_localize_script(
            'nf-hubspot/admin-settings',
            'params',
            [
                'updated' => __('Updated', 'ninja-forms-hubspot'),
                'adminSettingsNonce' => $nonce
            ]
    );     
    wp_enqueue_script('nf-hubspot/admin-settings');
});
