<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-329e76
Date:    2018-03-01 15:23:17
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-329e76",
    "email": {
        "to": "aramparunak@gmail.com",
        "cc": "",
        "bcc": "aram@hoopscollege.com",
        "subject": "Registration for Practice Plan Review",
        "template": "{dataTable}",
        "fromName": "Aram Parunak CBO Hoops College",
        "sendmail_from": "aramparunak@gmail.com"
    },
    "admin": {
        "users": "admin:ef238",
        "dataDelivery": "emailOnly"
    },
    "thankyou": {
        "url": "..\/coaches.html",
        "message": "Thank you for your submission. You are on your way back to Hoops College.",
        "seconds": "5"
    },
    "autoResponse": {
        "includeAttachments": false,
        "subject": "Registration Confirmation for Hoops College,
        "template": "Thank you for letting us review your practice plans! Hoops College staff will be in touch with you in the next 48 hours to keep things moving forward. Hoops College Staff",
        "replyToName": "Aram Parunak CBO Hoops College",
        "replyTo": "aram@hoopscollege.com"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "aramparunak@gmail.com",
        "password": "D1ck0987!",
        "port": "465",
        "security": "ssl"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
         {
            "label": "Current Position",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f17",
            "cid": "c93"
        },
        {
            "label": "Years in Current Position",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c98",
            "id": "f18"
        },
        {
            "label": "Years Coaching Overall",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c104",
            "id": "f19"
        },
          {
            "label": "Current Record",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f10",
            "cid": "c57"
        },
         {
            "label": "What is your best finish in the last 4 years?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c110",
            "id": "f20"
        },
        {
            "label": "Where do you finish in a typical season? ",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c116",
            "id": "f21"
        },
         {
            "label": "DESIRED identity",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "checked": null,
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "checked": null,
                        "value": "8"
                    },
                    {
                        "label": "9",
                        "checked": null,
                        "value": "9"
                    },
                    {
                        "label": "10",
                        "checked": null,
                        "value": "10"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "col-2"
                }
            },
            "id": "f6",
            "cid": "c35"
        },
        {
            "label": "CURRENT ID",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f22",
            "cid": "c122"
        },
         {
            "label": "Going well",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "checked": null,
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "checked": null,
                        "value": "8"
                    },
                    {
                        "label": "9",
                        "checked": null,
                        "value": "9"
                    },
                    {
                        "label": "10",
                        "checked": null,
                        "value": "10"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "col-2"
                }
            },
            "cid": "c46",
            "id": "f8"
        },
                {
            "label": "Root for good",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f9",
            "cid": "c52"
        },
        {
            "label": "Not Going well",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "checked": null,
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "checked": null,
                        "value": "8"
                    },
                    {
                        "label": "9",
                        "checked": null,
                        "value": "9"
                    },
                    {
                        "label": "10",
                        "checked": null,
                        "value": "10"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "col-2"
                }
            },
            "cid": "c127",
            "id": "f23"
        },
      
        {
            "label": "NEgative Root",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f27",
            "cid": "c148"
        },
         {
            "label": "Always make time",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "No time for",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f7",
            "cid": "c41"
        },
         {
            "label": "Live With",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f30",
            "cid": "c163"
        },
        {
            "label": "1st half players",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "1",
                    "initval": "5",
                    "min": "5",
                    "max": "15"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "id": "f14",
            "cid": "c77"
        },
        {
            "label": "underclass contributors",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "1",
                    "initval": "5",
                    "min": "5",
                    "max": "15"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c82",
            "id": "f15"
        },
        {
            "label": "how will underclassmen impact future",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f16",
            "cid": "c88"
        },
       {
            "label": "family",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f34",
            "cid": "c186"
        },
        {
            "label": "spiritual",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c191",
            "id": "f35"
        },
        {
            "label": "Self",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c197",
            "id": "f36"
        },
        {
            "label": "Team",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c203",
            "id": "f37"
        },
        {
            "label": "Students",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c209",
            "id": "f38"
        },
        {
            "label": "Friends",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c215",
            "id": "f39"
        },
        {
            "label": "Family",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c221",
            "id": "f40"
        },
        {
            "label": "Spirituality",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c227",
            "id": "f41"
        },
        {
            "label": "Self",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c233",
            "id": "f42"
        },
        {
            "label": "Team",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c239",
            "id": "f43"
        },
        {
            "label": "Students",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c245",
            "id": "f44"
        },
        {
            "label": "Friends",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c251",
            "id": "f45"
        },
            {
            "label": "MOnth1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "id": "f59",
            "cid": "c335"
        },
        {
            "label": "Month2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "cid": "c340",
            "id": "f60"
        },
        {
            "label": "Day1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "id": "f61",
            "cid": "c347"
        },
        {
            "label": "Day 2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "cid": "c352",
            "id": "f62"
        },
        {
            "label": "Time1",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f63",
            "cid": "c358"
        },
        {
            "label": "Time2",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f64",
            "cid": "c363"
        },
         
        {
            "label": "Textbox",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f28",
            "cid": "c153"
        },
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
     
        {
            "label": "School",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c30"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f4",
            "cid": "c25"
        },
       
    
      
        {
            "label": "Textbox",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f11",
            "cid": "c62"
        },
        {
            "label": "Textbox",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f12",
            "cid": "c67"
        }, 
        {
            "label": "Paragraph",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f29",
            "cid": "c158"
        },
  
        {
            "label": "Paragraph Copy",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "cid": "c168",
            "id": "f31"
        },
        {
            "label": "Paragraph Copy Copy",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "cid": "c174",
            "id": "f32"
        },
        {
            "label": "Paragraph Copy Copy Copy",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "cid": "c180",
            "id": "f33"
        },
        
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c257",
            "id": "f46"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c263",
            "id": "f47"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c269",
            "id": "f48"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c275",
            "id": "f49"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c281",
            "id": "f50"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c287",
            "id": "f51"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c293",
            "id": "f52"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c299",
            "id": "f53"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c305",
            "id": "f54"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c311",
            "id": "f55"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c317",
            "id": "f56"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c323",
            "id": "f57"
        },
        {
            "label": "Select Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy Copy",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c329",
            "id": "f58"
        },
   
        {
            "label": "Textbox",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f65",
            "cid": "c369"
        },
        {
            "label": "Textbox",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f66",
            "cid": "c374"
        },
        {
            "label": "Paragraph",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f67",
            "cid": "c379"
        },
        {
            "label": "Paragraph",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f68",
            "cid": "c384"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": "",
    "twilio": {
        "toPhone": "9196022532"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class