<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-aa48ca
Date:    2018-02-14 10:31:19
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-aa48ca",
     "email": {
        "to": "aramparunak@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "Registration Confirmation Coach's Consultation (Online)",
        "template": "{dataTable}",
        "sendmail_from": "dickran@gmail.com",
        "fromName": "Aram Parunak"
    },
    "admin": {
        "users": "admin:8ec1b, aram:D1ck0987!",
        "dataDelivery": "emailOnly"
    },
    "thankyou": {
        "url": "..\/coaches.html",
        "message": "",
        "seconds": "4"
    },
    "autoResponse": {
        "includeAttachments": false,
        "subject": "Registration Confirmation for Hoops College",
        "template": "Coach, We are so excited to start the conversation! Hoops College staff will be in touch with you in the next 48 hours to finalize your Coach’s Consultation. Hoops College Staff",
        "replyTo": "aram@hoopscollege.com",
        "replyToName": "Aram Parunak"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
      "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "aramparunak@gmail.com",
        "password": "D1ck0987!",
        "port": "465",
        "security": "ssl",
        "debug": false
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": true,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Please enter a phone number so that we can contact you."
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Other Info",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "time 2",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "placeholder": "Time"
            },
            "id": "f12",
            "cid": "c71",
            "labelHide": true
        },
        {
            "label": "time 1",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "placeholder": "Time"
            },
            "cid": "c76",
            "labelHide": true,
            "id": "f13"
        },
        {
            "label": "Prep Game Situations",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f14",
            "cid": "c85"
        },
        {
            "label": "Prep Personnel",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c90",
            "id": "f15"
        },
        {
            "label": "Schemes 2nd half",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c96",
            "id": "f16"
        },
        {
            "label": "Schemes 2nd game",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c102",
            "id": "f17"
        },
        {
            "label": "Prepare In Game",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c108",
            "id": "f18"
        },
        {
            "label": "Watch FIlm",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c114",
            "id": "f19"
        },
        {
            "label": "Prep Opponent OFfense",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c120",
            "id": "f20"
        },
        {
            "label": "Prep Opponent Defense",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c126",
            "id": "f21"
        },
        {
            "label": "Special Situations",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c132",
            "id": "f22"
        },
        {
            "label": "Communication",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c138",
            "id": "f23"
        },
        {
            "label": "Assistants Roles in practice",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c144",
            "id": "f24"
        },
        {
            "label": "Assistant Roles in Games",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Very Important",
                        "checked": false,
                        "value": "Very"
                    },
                    {
                        "label": "Somewhat Important",
                        "checked": false,
                        "value": "somewhat"
                    },
                    {
                        "label": "Not an Emphasis",
                        "checked": false,
                        "value": "not"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c150",
            "id": "f25"
        },
        {
            "label": "Purpose_Prepare_Games",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f29",
            "cid": "c173"
        },
        {
            "label": "Purpose_Skills",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c178",
            "id": "f30"
        },
        {
            "label": "Purpose_Identity",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c184",
            "id": "f31"
        },
        {
            "label": "Purpose_Team_Concepts",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c190",
            "id": "f32"
        },
        {
            "label": "Purpose_Roles",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c196",
            "id": "f33"
        },
        {
            "label": "Purpose_Habits",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c202",
            "id": "f34"
        },
        {
            "label": "Qualities_Fun",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c208",
            "id": "f35"
        },
        {
            "label": "Qualities_Engagement",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c214",
            "id": "f36"
        },
        {
            "label": "Qualities_Conditioning",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c220",
            "id": "f37"
        },
        {
            "label": "Qualities_Challenging",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c226",
            "id": "f38"
        },
        {
            "label": "Qualities_Chemistry",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c232",
            "id": "f39"
        },
        {
            "label": "Qualities_Competition",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c238",
            "id": "f40"
        },
        {
            "label": "Janssen",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "checked": null,
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "checked": null,
                        "value": "8"
                    }
                ],
                "presetJson": ""
            },
            "id": "f41",
            "cid": "c244"
        },
        {
            "label": "Time Allocation",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    },
                    {
                        "label": "7",
                        "checked": null,
                        "value": "7"
                    },
                    {
                        "label": "8",
                        "checked": null,
                        "value": "8"
                    }
                ],
                "presetJson": ""
            },
            "cid": "c249",
            "id": "f42"
        },
        {
            "label": "Culture",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "id": "f43",
            "cid": "c255"
        },
        {
            "label": "Game Strategy",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c260",
            "id": "f44"
        },
        {
            "label": "Team Offense",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c266",
            "id": "f45"
        },
        {
            "label": "Team Defense",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c272",
            "id": "f46"
        },
        {
            "label": "Practice Planning",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c278",
            "id": "f47"
        },
        {
            "label": "Individual Skills",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": true,
                    "step": "5",
                    "initval": "20",
                    "min": "0",
                    "max": "60"
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                }
            },
            "cid": "c284",
            "id": "f48"
        },
        {
            "label": "Month1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "id": "f49",
            "cid": "c184"
        },
        {
            "label": "Month2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "cid": "c189",
            "id": "f50"
        },
        {
            "label": "Day1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "id": "f51",
            "cid": "c195"
        },
        {
            "label": "Day2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "cid": "c200",
            "id": "f52"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],

    "licenseKey": "JF-5LF697510M7667901"
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class