<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-b8e9ae
Date:    2018-02-28 10:10:05
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-b8e9ae",
    "email": {
        "to": "aramparunak@gmail.com",
        "cc": "",
        "bcc": "aram@hoopscollege.com",
        "subject": "Registration for Planning Period",
        "template": "{dataTable}",
        "fromName": "Aram Parunak",
        "sendmail_from": "aramparunak@gmail.com"
    },
    "admin": {
        "users": "admin:5cf45",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "..\/coaches.html",
        "message": "Thank you for your submission. You are on your way back to Hoops College.",
        "seconds": "5"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "Registration Confirmation for Hoops College",
        "template": "Coach, Thank you for joining the community! Hoops College staff will be in touch with you in the next 48 hours to set up your login for The Planning Period. Hoops College Staff",
        "replyToName": "Aram Parunak CBO Hoops College",
        "replyTo": "aram@hoopscollege.com"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.gmail.com",
        "user": "aramparunak@gmail.com",
        "password": "D1ck0987!",
        "port": "465",
        "security": "ssl"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
       
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "sender": true,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "School",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f5",
            "cid": "c30"
        },
        {
            "label": "Current Position",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f6",
            "cid": "c35"
        },
        {
            "label": "Years in Current Position",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c41",
            "id": "f7"
        },
        {
            "label": "Years Coaching Overall",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c47",
            "id": "f8"
        },
        {
            "label": "Best in Last 4",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c53",
            "id": "f9"
        },
        {
            "label": "Typical Finish",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c59",
            "id": "f10"
        },
        {
            "label": "Current Record",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f11",
            "cid": "c65"
        },
       
        {
            "label": "Obstacles",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f13",
            "cid": "c75"
        },
        {
            "label": "Opportunities",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f14",
            "cid": "c80"
        },
           {
            "label": "Strengths",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f33",
            "cid": "c188"
        },
         {
            "label": "Weaknesses",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "Family",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f15",
            "cid": "c85"
        },
        {
            "label": "Spirit",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c90",
            "id": "f16"
        },
        {
            "label": "Self",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c96",
            "id": "f17"
        },
        {
            "label": "Team",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c102",
            "id": "f18"
        },
        {
            "label": "Students",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c108",
            "id": "f19"
        },
        {
            "label": "Friends",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c114",
            "id": "f20"
        },
        {
            "label": "Family",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c120",
            "id": "f21"
        },
        {
            "label": "Spirit",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c126",
            "id": "f22"
        },
        {
            "label": "Self",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c132",
            "id": "f23"
        },
        {
            "label": "Team",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c138",
            "id": "f24"
        },
        {
            "label": "Students",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c144",
            "id": "f25"
        },
        {
            "label": "Friends",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "value": "4",
                        "checked": null
                    },
                    {
                        "label": "5",
                        "value": "5",
                        "checked": null
                    },
                    {
                        "label": "6",
                        "value": "6",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c150",
            "id": "f26"
        },
        {
            "label": "MOnth2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "id": "f27",
            "cid": "c156"
        },
        {
            "label": "Month1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "January"
                    },
                    {
                        "checked": false,
                        "label": "February"
                    },
                    {
                        "checked": false,
                        "label": "March"
                    },
                    {
                        "checked": false,
                        "label": "April"
                    },
                    {
                        "checked": false,
                        "label": "May"
                    },
                    {
                        "checked": false,
                        "label": "June"
                    },
                    {
                        "checked": false,
                        "label": "July"
                    },
                    {
                        "checked": false,
                        "label": "August"
                    },
                    {
                        "checked": false,
                        "label": "September"
                    },
                    {
                        "checked": false,
                        "label": "October"
                    },
                    {
                        "checked": false,
                        "label": "November"
                    },
                    {
                        "checked": false,
                        "label": "December"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "months.json",
                "multiple": false
            },
            "cid": "c161",
            "id": "f28"
        },
        {
            "label": "Day1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "id": "f29",
            "cid": "c167"
        },
        {
            "label": "Day2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "checked": false,
                        "label": "Monday"
                    },
                    {
                        "checked": false,
                        "label": "Tuesday"
                    },
                    {
                        "checked": false,
                        "label": "Wednesday"
                    },
                    {
                        "checked": false,
                        "label": "Thursday"
                    },
                    {
                        "checked": false,
                        "label": "Friday"
                    },
                    {
                        "checked": false,
                        "label": "Saturday"
                    },
                    {
                        "checked": false,
                        "label": "Sunday"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "days.json",
                "multiple": false
            },
            "cid": "c172",
            "id": "f30"
        },
        {
            "label": "Time1",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f31",
            "cid": "c178"
        },
        {
            "label": "Time2",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "id": "f32",
            "cid": "c183"
        },
      
         {
            "label": "Multiple Choice",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Option 1",
                        "checked": false,
                        "value": "1"
                    },
                    {
                        "label": "Option 2",
                        "checked": false,
                        "value": "2"
                    },
                    {
                        "label": "Option 3",
                        "checked": false,
                        "value": "3"
                    },
                    {
                        "label": "4",
                        "checked": null,
                        "value": "4"
                    },
                    {
                        "label": "5",
                        "checked": null,
                        "value": "5"
                    },
                    {
                        "label": "6",
                        "checked": null,
                        "value": "6"
                    }
                ],
                "presetJson": ""
            },
            "id": "f12",
            "cid": "c70"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": "",
    "twilio": {
        "toPhone": "9196022532"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class